name: Manual Update Feishu SFC Companies Work Items
on:
  workflow_dispatch:
    inputs:
      ids:
        description: "update work items with ids split by comma, e.g. 1,2,3"
        required: false
      all:
        description: "update all work items"
        required: false

jobs:
  export:
    name: Start update SFC Companies work items
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          branch: main

      - uses: oven-sh/setup-bun@v1

      - name: Run update SFC Companies work items
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          PLUGIN_SECRET: ${{ secrets.PLUGIN_SECRET }}
          SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
          SUPABASE_EMAIL: ${{ secrets.SUPABASE_EMAIL }}
        run: |
          bun install
          bun run src/feishu/index.ts --ids=${{ inputs.ids }} --all=${{ inputs.all }}
