name: Update SFC Companies Work Items
on:
  workflow_dispatch:
    inputs:
      ids:
        description: "update work items with ids split by comma, e.g. 1,2,3"
        required: false
      all:
        description: "update all work items"
        required: false

jobs:
  export:
    name: Start update SFC Companies work items
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          branch: main

      - uses: oven-sh/setup-bun@v1
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          PLUGIN_SECRET: ${{ secrets.PLUGIN_SECRET }}
          USER_KEY: ${{ secrets.USER_KEY }}
          WORK_ITEM_TYPE_KEY: ${{ secrets.WORK_ITEM_TYPE_KEY }}
          TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
          PROJECT_KEY: ${{ secrets.PROJECT_KEY }}
          PLUGIN_ID: ${{ secrets.PLUGIN_ID }}

      - name: Run update SFC Companies work items
        run: |
          bun install
          bun run src/feishu/index.ts --ids=${{ inputs.ids }} --all=${{ inputs.all }}