name: Scheduled Check and Update SFC Companies Work Items
on:
  schedule:
    # Every 1 days at 00:10
    - cron: "10 0 */1 * *"

jobs:
  export:
    name: Check and update SFC Companies work items
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          branch: main

      - uses: oven-sh/setup-bun@v1

      - name: Check if has new sfc entry and update!
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          PLUGIN_SECRET: ${{ secrets.PLUGIN_SECRET }}
          USER_KEY: ${{ secrets.USER_KEY }}
          WORK_ITEM_TYPE_KEY: ${{ secrets.WORK_ITEM_TYPE_KEY }}
          TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
          PROJECT_KEY: ${{ secrets.PROJECT_KEY }}
          PLUGIN_ID: ${{ secrets.PLUGIN_ID }}
          SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
          SUPABASE_EMAIL: ${{ secrets.SUPABASE_EMAIL }}
        run: |
          bun install
          bun run hk_sfc
