name: Scheduled Check and Update SFC Companies Work Items
on:
  workflow_dispatch:
  schedule:
    # At 00:10 on Saturday.
    - cron: "10 0 * * 6"

jobs:
  export:
    name: Check and update SFC Companies work items
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          branch: main

      - uses: oven-sh/setup-bun@v1

      - name: Check if has new sfc entry and update!
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          PLUGIN_SECRET: ${{ secrets.PLUGIN_SECRET }}
          SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
          SUPABASE_EMAIL: ${{ secrets.SUPABASE_EMAIL }}
        run: |
          bun install
          bun run src/feishu/scheduled.ts
